pluginManagement {
  repositories {
    mavenCentral()
    gradlePluginPortal()
  }
}

rootProject.name = 'febit-boot-parent'

boot 'boot-bom'
boot 'boot-dependencies'

boot 'boot'

boot 'boot-starter-webmvc'
boot 'boot-starter-jwt'
boot 'boot-starter-jooq'

def boot(String dir) {
  def name = ":febit-$dir"
  include name
  project(name).projectDir = file(dir)
}
