[versions]
hierynomus-license = '0.16.1'

febit-commons = '4.1.1'
febit-devkit = '1.6.2'

spring-boot = '4.1.1'
springdoc = '3.1.1'

[libraries]
febit-commons-bom = { module = 'org.febit:febit-commons-bom', version.ref = 'febit-commons' }
febit-commons-deps = { module = 'org.febit:febit-commons-dependencies', version.ref = 'febit-commons' }
spring-boot-deps = { module = 'org.springframework.boot:spring-boot-dependencies', version.ref = 'spring-boot' }
springdoc-openapi-bom = { module = 'org.springdoc:springdoc-openapi-bom', version.ref = 'springdoc' }

[plugins]
febit-bom = { id = 'org.febit.standard-bom', version.ref = 'febit-devkit' }
febit-codegen-module = { id = 'org.febit.codegen-module', version.ref = 'febit-devkit' }
febit-java = { id = 'org.febit.standard-java', version.ref = 'febit-devkit' }
febit-maven-publish = { id = 'org.febit.standard-maven-publish', version.ref = 'febit-devkit' }

license = { id = 'com.github.hierynomus.license', version.ref = 'hierynomus-license' }
